version: 0.0
os: linux
files:
  - source: s3://code-s3-pipeline/springBootApp/hellospringbootapp-0.0.1-SNAPSHOT.war
  destination: /home/ubuntu/deploy

hooks:
  BeforeInstall:
     - echo before install step
     #- location: scripts/before_install.sh
      #timeout: 300
      #runas: ubuntu

  AfterInstall:
    - echo after install step
    #- location: scripts/after_install.sh
      #timeout: 300
      #runas: ubuntu

  ApplicationStart:
    - echo start service
    #- location: scripts/start_server.sh
      #timeout: 300
      #runas: ubuntu

  ApplicationStop:
    - echo stop service
    #- location: scripts/stop_server.sh
      #timeout: 300
      #runas: ubuntu

  ValidateService:
    - echo before validation
    #- location: scripts/validate_service.sh
      #timeout: 300
      #runas: ubuntu
      
      
